<?php

namespace AppBundle\Repository;

/**
 * SearchTripRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SearchTripRepository extends \Doctrine\ORM\EntityRepository
{
}
